spring:
  datasource:
    url: jdbc:mysql://localhost:3306/themoviedb
    username: root
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
